src/SerializeSourcemap.cc

@pksunkara please merge urgently, it is hotfix, without this cannot drafter be builded

fix calling of method renamed while review

---

Gemfile.lock
appveyor.yml
features/sourcemap.feature
src/stream.h

Add fstream open in `binary` mode.
In text mode on windows is char `\n` automatic transformed into `\r\n`
This fix avoid this behaviour

Fix fstream behaviour on windows 

---

README.md
features/fixtures/ast.json
features/fixtures/ast.yaml
src/Serialize.cc
src/Serialize.h
src/SerializeAST.cc
src/SerializeResult.cc
test/fixtures/annotations-with-warning.ast.json
test/fixtures/annotations-with-warning.result-with-sourcemap.json
test/fixtures/annotations-with-warning.result.json

Since the serialisation has moved to drafter, I am updating them here. Sorry, I forgot about making this PR earlier.
AST version = 3.0
Parse Result version = 2.1

Update AST and Parse Result versions

---

configure

In Python 2.6 `sys.version_info` is a tuple, so doesn't have a `.major` attribute.
Using the index access method works in both 2.6, 2.7 and 3

Make version check work in Python <2.7

---

features/fixtures/ast.json
features/fixtures/ast.yaml
src/RefractAST.cc
src/SerializeAST.cc
src/refract/ExpandVisitor.cc
test/fixtures/mson-array-typed-content.apib
test/fixtures/mson-array-typed-content.json
test/fixtures/mson-resource-anonymous.apib
test/fixtures/mson-resource-anonymous.json
test/fixtures/mson-resource-nested-inheritace.apib
test/fixtures/mson-resource-nested-inheritace.json
test/fixtures/mson-resource-nested-member.apib
test/fixtures/mson-resource-nested-member.json
test/fixtures/mson-resource-nested-mixin.apib
test/fixtures/mson-resource-nested-mixin.json
test/fixtures/mson-resource-primitive-mixin.apib
test/fixtures/mson-resource-primitive-mixin.json
test/fixtures/mson-resource-resolve-basetype.apib
test/fixtures/mson-resource-resolve-basetype.json
test/fixtures/mson-resource-unresolved-reference.apib
test/fixtures/mson-resource-unresolved-reference.json
test/test-RefractTest.cc

Ready for review
Changes:
- backported testcases from drafter.js
- MSON array nested types expansion
DO NOT MERGE - it probably break backward compatibility with **Extend JSON** where is @pksunkara working on.

refract backport drafter.js tests

---

src/refract/ExpandVisitor.cc
test/fixtures/mson-inheritance.json

This fix resolve bug with copying element name while expanding "deeply" inherited elements

Refract - disable copy of element name while expnading inheritance

---

src/RefractAST.cc
src/refract/ExpandVisitor.cc
src/refract/TypeQueryVisitor.h
test/fixtures/mson-inheritance.json

- "Expand" envolope Element is now same type (in C++ meaning) as referenced object
- Original Element is cloned with meta && attributes
replace PR #57

Refract - fix array expansion

---

README.md

I made a package to install Drafter on Arch Linux, this adds a link to it in the README file.

Added link to AUR package for Arch Linux installations

---

src/RefractAST.cc
src/refract/Element.h
src/refract/ExpandVisitor.cc
src/refract/IsExpandableVisitor.cc
src/refract/SerializeCompactVisitor.cc
src/refract/SerializeVisitor.cc
test/fixtures/mson-mixin.apib
test/fixtures/mson-mixin.json
test/fixtures/mson-resource-nested-mixin.json
test/fixtures/render-object-mixin.json

Expansion via `attributes.resolved` as defined in https://github.com/refractproject/refract-spec/blob/master/namespaces/mson-namespace.md#type-reference-ref-element

Refract - implement Ref Element expansion

---

src/RefractAST.cc
src/refract/AppendDecorator.h

This change explicitly includes the `iterator` header in the
files using `std::back_iterator`. In some versions of Microsoft
Visual Studio, this header is not automatically included and
it leads to compile errors. See:
http://stackoverflow.com/questions/2959234/vs2008-vs2010-leads-to-cryptic-stl-errors
https://ci.appveyor.com/project/Apiary/protagonist/build/1.0.107

Fix build on Windows

---

features/fixtures/ast.json
features/fixtures/ast.yaml
features/fixtures/refract.json
features/fixtures/refract.yaml
src/RefractAPI.cc
src/RefractAPI.h
src/SerializeAST.cc
src/SerializeAST.h
test/draftertest.h
test/fixtures/api/attributes-references.json
test/fixtures/render/array-mixin.json
test/fixtures/render/array-ref-array.json
test/fixtures/render/array-ref-object.json
test/fixtures/render/inheritance-array-sample.json
test/fixtures/render/inheritance-object-sample.json
test/fixtures/render/mixin-array-sample.json
test/fixtures/render/mixin-object-sample.json
test/fixtures/render/object-mixin.json
test/fixtures/render/object-ref-object.json
test/test-RefractDataStructureTest.cc

This PR does a few things:
1. Removes Data Structure expansion from APIB Refract
2. Adds an option for `drafter::WrapBlueprint` for data structure expansion so that the MSON refract tests can use it to check the intermediate step of expanding refract for rendering.
3. Change the above mentioned tests to use the above mentioned option.

Removed Data Structure expansion from APIB Refract

---

src/RefractAPI.cc
src/RefractDataStructure.cc
src/refract/Element.h

This PR adds the `iterator` C++ header to the files wherever it was required to fix the compilation errors on windows for protagonist.

Add iterator header wherever it's missing

---

README.md

I recently created [Drafter-php](https://github.com/hendrikmaus/drafter-php) as wrapper around the Drafter command line tool.
The package can be installed using composer.
Drafter command line tool has to be installed aside to it. The readme contains some basic instructions on how to do that with composer, but first of all references the Drafter repositories installation guides.
If you consider this a binding, this pull request would add it to the readme.
I am looking forward to your feedback.
Cheers,
Hendrik

Add Drafter-php as binding for the PHP language

---

src/Render.cc
src/Render.h
test/fixtures/render/content-type.apib
test/fixtures/render/content-type.json
test/test-RenderTest.cc

This PR makes sure that when rendering we don't try to match the content-types exactly. This PR also fixes a small case where a value is not passed by reference.

Don't exact match for content-type in rendering

---

src/RefractDataStructure.cc
test/fixtures/mson/array-reference.apib
test/fixtures/mson/array-reference.json
test/fixtures/mson/reference-override.apib
test/fixtures/mson/reference-override.json
test/test-RefractDataStructureTest.cc

This PR updates the snowcrash submodule to the latest. This PR also adds tests to make sure:
1. Named type references in an array which is nested are getting expanded
2. Overriding named type references should be working
PS: After this PR is merged, #39 can no longer be directly merged and need to use CLI to merge it. Since, we can't rebase the `shared/refract` branch, this is okay.

Updates snowcrash and adds tests

---

features/fixtures/refract.json
features/fixtures/refract.yaml
src/RefractAPI.cc
test/fixtures/api/resource-parameters.json

This PR makes sure that whenever a parameter has `enum`, then the `samples` and `default` are correctly getting serialized.
@klokane Please review and merge.

Correctly serialize parameter refract for enum

---

src/RefractDataStructure.cc
src/Serialize.cc
src/Serialize.h
src/SerializeAST.cc
src/refract/RenderJSONVisitor.cc
test/fixtures/render/nullable.apib
test/fixtures/render/nullable.json
test/test-RenderTest.cc

+ adding `nullable` type attribute based on apiaryio/mson#38 this should resolve #106
+ updating `ext/snowcrash` to `f9942fefa531626d3406effdad5d1b35ed4f0120` which was the addition of `nullable` to snowcrash in apiaryio/snowcrash#349

Adding `nullable` attribute

---

README.md

Fixes after https://github.com/refractproject/refract-spec/pull/47

Fix parse result namespace link

---

src/RefractDataStructure.cc
src/refract/AppendDecorator.h
test/fixtures/mson/enum-variants.apib
test/fixtures/mson/enum-variants.json
test/test-RefractDataStructureTest.cc

Closes #97 
Changes in `ExtractValueMember<T>`.
- now just extracting data from `mson::ValueMember` instead of manipulation with *Element*
(like `ExtractTypeInfo<>`)
- `TypeSectionData` renamed to `ElementData`
- `TransformTypeSectionData` renamed to `TransformElementData`
- add fixtures to handle improved enum|array parsing

Improve enum parsing

---

src/Render.cc
src/Serialize.cc
src/Serialize.h

This PR along with #126 removes most of the WITH_REFRACT macros except the main one. This PR fixes #103

Removed WITH_REFRACT from most places

---

src/SerializeResult.cc
src/SerializeResult.h

This PR makes sure that the `warnings` key in `drafter::WrapResult` should be an empty array when no warnings are present. I am doing this because that is how protagonist has been serialising until now. And since `WrapResult` is synonymous with the output from protagonist, we need to make sure they are similar.
This PR also does the following minor things:
* Expose `drafter::WrapAnnotation` so that protagonist can use it.
* Updates the sos submodule.
Blocked by #126 and need to be rebased once that is merged.

Key 'warnings' in WrapResult should be an empty array

---

drafter.xcodeproj/project.pbxproj

Seem's this project uses 4 spaces so I'm explicitly setting this in the project. My global Xcode defaults differ.

Set indentation to 4 spaces in Xcode project

---

emcc/release.sh

Fixes the release issue from the latest pre-release. There was a bug in the script where it tried to upload two files to the same name.
Both files are now uploaded to the latest release; this fix will apply to the next release:
https://github.com/apiaryio/drafter/releases/tag/v2.0.0-pre.0
Thanks!

Fix upload asset name

---

emcc/post.js

Lib crashed when I try to parse specs with Unicode symbols in them.
I debug issue and took solution from here https://github.com/kripken/emscripten/blob/42fb486c53d627b203b77af6e5d0c088c0ad03ad/src/preamble.js#L158
Please add Unicode tests to your testsuite.

Fix memory allocation - emscripten

---

emcc/release.sh

The `.npmrc` file would cause issues when `NPM_TOKEN` is not defined, so it was removed in f0df9c07795b0b5dfc3bc7dc98e499a8468f4dce. That inadvertently broke the release script, so this PR fixes it by creating the file on the fly. I chose this instead of [another method](http://glebbahmutov.com/blog/automatically-publish-to-npm/) because it [keeps my password a secret](http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules) to those with access to the CI host configuration.

Use NPM_TOKEN CI host env var for releases

---

appveyor.yml
src/SerializeAST.cc

This PR also adds matrix build support for MSVC2012 in appveyor along with MSVC2013.
Fixes #149

Added support for MSVC2012.

---

README.md
src/Serialize.h
src/cdrafter.cc
src/main.cc
test/draftertest.h
test/test-RefractDataStructureTest.cc

This PR also adds a few convenience constructors to `WrapperOptions`.

Give priority to sourcemap in wrapper options

---

src/SerializeResult.cc
src/SerializeResult.h

Expose `WrapAnnotation()` back to public

---

package.json

Without this fix `browserify` give following error:
```
Running "browserify:main" (browserify) task
>> Error: Cannot find module 'ws' from '/home/ivang/dev/api-spec-converter/node_modules/drafter.js/emcc'
```
Inside `drafter.nomem.js`:
```js
var WebSocket = ENVIRONMENT_IS_NODE ? require("ws") : window["WebSocket"];
```
Problem that `browserify` can't statically analyze `ENVIRONMENT_IS_NODE` value.
It browser if will always evaluate to `false`, so it safe to disable `ws` module.
This issue significantly blocks me, pleaser merge it and release updated NPM package.

Fix missing 'ws' module during browserify

---

src/refract/JSONSchemaVisitor.cc
src/refract/JSONSchemaVisitor.h

- DRY primitive types
- Remove unnecessary heap allocations

Refactoring the JSONSchemaVisitor

---

circle.yml
emcc/release.sh
tools/make-tarball.sh
tools/release.sh

Unfortunately the "Source Code" tarballs that GitHub creates won't include the recursive submodules in the source and therefore are not usable to install drafter. The only way to install drafter is via a recursive git checkout.
This makes it difficult to package since it relies on git and many packaging systems don't allow this (Debian, Arch linux etc). This change will also allow us to provide a non-HEAD homebrew formula that uses the tarball so we can allow `brew update` to actually work.
Therefore, I've modified the release process that Circle CI runs to package up all the source code. This is broken up into two components, the first a script to generate a tarball. Here is the usage/showing that it works:
```shell
$ ./tools/make-tarball.sh 2.0.0
Exporting to …
```

Upload release tarballs to GitHub release

---

Makefile

This change splits out BINDIR from DESTDIR, traditionally DESTDIR is not the "bin" dir on other makefiles and this makes our makefile work similar to others.
This change also makes sure the bin directory exists using mkdir in the install phase.

DESTDIR shouldn't be the BINDIR in the makefile

---

README.md
emcc/post.js

drafter.js should be a drop in replacemenet so that it can be used where
native code is not possible or implies big overhead and parsing times are
not critical, i.e. dredd in CI where 10s parsing time extra is much less
then building protagonist from source.

Changes drafter.js API to protagonist.

---

src/RefractAPI.cc
src/Render.cc
test/fixtures/api/schema-body.apib
test/fixtures/api/schema-body.json
test/fixtures/api/schema-body.sourcemap.json
test/test-RefractAPITest.cc
test/test-RefractSourceMapTest.cc

This PR handles the case where a user might give the content type of a messageBody to be `application/schema+json`.

Handle JSON Schema rendering for messageBody

---

circle.yml
src/Render.cc

This pull request fixes a warning introduced by #234 by handling the `UndefinedRenderFormat` case in a switch statement.
I've also added the `CXXFLAG` `-Werror` in CI so we treat warnings as errors during out CI. This allows us to prevent warnings being introduced into master, but also allows people to still compile Drafter providing there are warnings introduced.

Handle `UndefinedRenderFormat` in switch statement

---

.gitattributes
appveyor.yml
vcbuild.bat

This PR updates Snow Crash to the latest master in order to bring updated GYP version to support Microsoft Visual Studio 2015 (Microsoft Visual C++ 2015).
In addition it updates the Windows batch build file to support the `MSVC2015` option. The `.gitattributes` file is introduced to preserve LF line endings on Windows systems. Finally, the AppVeyor configuration has been changed to use the Visual Studio 2015 CTP image instead of previous Windows Server 2012.

Support for MSVS2015

---

src/RefractDataStructure.cc
test/fixtures/mson/regression-267.apib
test/fixtures/mson/regression-267.ast.json
test/test-RefractDataStructureTest.cc

While the type is the same as the default nested type, we would be causing recursion by calling ourself with the same arguments.
Fixes #267.
---
Perhaps there is a better solution, welcome to suggestions.

Prevent recursion while converting MSON type members to refract

---

features/fixtures/refract.sourcemap.json
features/fixtures/refract.sourcemap.yaml
src/RefractAPI.cc
test/fixtures/api/action-attributes.sourcemap.json
test/fixtures/api/action-parameters.sourcemap.json
test/fixtures/api/action.sourcemap.json
test/fixtures/api/advanced-action.sourcemap.json
test/fixtures/api/asset.sourcemap.json
test/fixtures/api/headers.sourcemap.json
test/fixtures/api/payload-attributes.sourcemap.json
test/fixtures/api/relation.sourcemap.json
test/fixtures/api/request-parameters.sourcemap.json
test/fixtures/api/resource-parameters.sourcemap.json
test/fixtures/api/schema-body.sourcemap.json
test/fixtures/api/schema-custom.sourcemap.json
test/fixtures/api/transaction.sourcemap.json
test/fixtures/api/xml-body.sourcemap.json

Source map info was not attached to httpRequest and httpResponse, see #259 for more info.
Closes #259

Attach source maps to httpRequest and httpResponse

---

appveyor.yml

Gem install takes forever installing pointless documentation

Speed up Appveyor CI time by disabling gem documentation

---

src/RefractDataStructure.cc
src/RefractDataStructure.h
src/Serialize.h
src/SerializeResult.cc
src/refract/SerializeCompactVisitor.cc
src/refract/SerializeCompactVisitor.h
src/refract/SerializeVisitor.cc
src/refract/SerializeVisitor.h
test/draftertest.h

Let's use `generateSourceMap` in all our codebases. It is the standard variable name for exporting source maps anyway.
PS: This doesn't change anything public facing.

Use generateSourceMap variable name

---

src/cdrafter.cc

We forgot to do this previously,

Switch on always on sourcemaps for cdrafter

---

src/SerializeResult.cc
src/cdrafter.cc
src/main.cc

Fixes #255.
@kylef Remember the small bit of code we talked about being nonsense? That is the one causing this issue.
PS: The current test blueprint we have is producing an error in drafter due to bug. Once that bug is fixed, this test won't work anymore. I am unable to get a blueprint which produces error in drafter (without it not being due to bug).
Maybe @w-vi or @klokane has a few ideas for the test case.

Make sure drafter errors are serialized as errors

---

drafter.gyp
src/ConversionContext.h
src/NamedTypesRegistry.cc
src/NamedTypesRegistry.h
src/RefractAPI.cc
src/RefractAPI.h
src/RefractDataStructure.cc
src/RefractDataStructure.h
src/RefractSourceMap.h
src/Render.cc
src/Render.h
src/Serialize.h
src/SerializeAST.cc
src/SerializeAST.h
src/SerializeResult.cc
src/SerializeResult.h
src/SerializeSourcemap.cc
src/SerializeSourcemap.h
src/cdrafter.cc
src/main.cc
test/draftertest.h

This patch additionaly remove global access point `GetNamedTypeRegistry()` instead is `Registry` instance stored in `ConversionContext`
To be thread safe we need add `RefractElementFactory` into Context too.
It will be done in next pull request

Introduce conversion context for thread safety

---

src/ConversionContext.h
src/RefractAPI.cc
src/RefractDataStructure.cc
src/SerializeResult.cc

This probably is not a complete list but there is no way how to trigger
those I leave it as is with the infrastructure in place so we can add
them anytime later.
Couldn't come with a test cases as all the errors are impossible to
trigger if there is not a bug in snowcrash.

Some errors should not stop parsing.

---

src/refract/ElementInserter.h
src/stream.h

I know we're exiting right away so it's not really a problem, but static analysers and such tools flag this as a leak.

Fix memory leak while failing to open file

---

src/SerializeResult.h

```
In file included from ../src/main.cc:22:
../src/ConversionContext.h:18:5: warning: 'ConversionContext' defined as a class here but previously declared as a struct
[-Wmismatched-tags]
class ConversionContext {
^
../src/SerializeResult.h:25:5: note: did you mean class here?
struct ConversionContext;
^~~~~~
class
```

ConversionContext is a class not struct

---

README.md

User's should prefer to use the new NPM drafter package from node instead of hitting Protagonist directly.
Depends on https://github.com/apiaryio/drafter-npm/pull/1

Reference drafter-npm for Node JS parsing

---

CHANGELOG.md
src/refract/RenderJSONVisitor.cc
src/refract/VisitorUtils.h
test/fixtures/render/enum-default.apib
test/fixtures/render/enum-default.ast.json
test/fixtures/render/enum-sample.apib
test/fixtures/render/enum-sample.ast.json
test/fixtures/schema/default-section.json
test/test-RenderTest.cc

The following precedence of enum examples with rendering will now be taken:
- Sample Values
- Default Values
- Values
- Nullable

Use default/sample enum values over members when rendering JSON

---

CHANGELOG.md
features/fixtures/blueprint.apib
features/fixtures/refract.sourcemap.json
features/fixtures/refract.sourcemap.yaml
src/RefractDataStructure.cc
src/Serialize.cc
src/Serialize.h
src/refract/JSONSchemaVisitor.cc
src/refract/JSONSchemaVisitor.h
test/fixtures/schema/array-fixed-type.apib
test/fixtures/schema/array-fixed-type.json
test/fixtures/schema/object-fixed-type-named-type.apib
test/fixtures/schema/object-fixed-type-named-type.json
test/fixtures/schema/object-fixed-type-values.apib
test/fixtures/schema/object-fixed-type-values.json
test/fixtures/schema/object-fixed-type.apib
test/fixtures/schema/object-fixed-type.json
test/test-SchemaTest.cc

I do not know should fixed-type attribute work for other types (strings, enums & etc). If it should work - please describe me how. Also I've adjust tests for last revision of snowcrash library.
Based on https://github.com/apiaryio/mson/issues/66

Add fixed-type support for arrays and objects

---

README.md

drafter-git our package is outdated, incorrect and broken. It would be better to point to the stable non-git version.

Link to Drafter AUR package

---

src/NamedTypesRegistry.cc

Partially solves #401. Allowing reserved keywords altogether has some consequences which need to be solved separately.

fix: Improve error message when using keywords

---

Makefile
drafter.xcodeproj/project.pbxproj
test/test-CAPI.c

This is to allow the protagonist to wrap the sos object in v8.
Otherwise, it will have to JSON parse the returned string by
drafter which will be a performance issue.

chore: Maintenance of C API

---

README.md

DrafterPy is as simple Python I made. I hope you like it.

Add DrafterPy into bindings list.

---

.gitmodules

git clone --recursive did not work, caused by a submodule reference using git:// instead of https://.

Fix url protocol of submodule /test/vendor/catch

---

features/step_definitions/file_content_step.rb

This makes the cucumber integration tests respect the `GENERATE` env variable to save new ASTs. This is the same behaviour as the main tests: https://github.com/apiaryio/drafter/blob/master/test/draftertest.h#L166

fix(integration tests): Respect GENERATE env variable

---

src/refract/JSONSchemaVisitor.cc
src/refract/JSONSchemaVisitor.h
test/fixtures/oneof/required.apib
test/fixtures/oneof/required.json
test/fixtures/oneof/required2.apib
test/fixtures/oneof/required2.json
test/test-OneOfTest.cc

This PR solves problem described in #452, but I think a bit of refactoring is required. It's possible to make it in separate PR or in this one.
Functions `void JSONSchemaVisitor::operator()(const OptionElement& e)` and `void JSONSchemaVisitor::operator()(const ObjectElement& e)` have a lot of common code (MemberElement & SelectElement processing, required attributes calculation) and I think this code a bit dirty: it's difficult to understand Select -> Option -> Select chain processing. This refactoring may take some time and it's difficult to estimate how much time it will be.
// UPDATE: refactoring complete

fix required attribute processing for json schema of oneOf

---

test/fixtures/schema/array-restricted-to-type.json
test/fixtures/schema/array-restricted-to-types-complex.json
test/fixtures/schema/array-restricted-to-types.json
test/test-SchemaTest.cc

Since #193 was resolved, this fixture can be enabled (and updated to new serialisation).

Enable array-restricted-to-type test fixture

---

CHANGELOG.md
README.md

Since we are near to releasing Drafter 4, this gives us another opportunity to make breaking changes in terms of supported compilers. I would propose we move to the following minimum versions:
| Compiler | Minimum Supported Version |
|----------|---------------------------|
| Clang    | 4.0 |
| GCC      | 5.3 |
| MSVC++   | 2015 |
This would allow us to make use of most [C++14 features and a few C++17 features](http://en.cppreference.com/w/cpp/compiler_support). I do not believe that supporting older compilers is as important as it once used to be, now that we have a pure JavaScript version of Drafter, the minimum compiler version doesn't add a barrier to using the API Blueprint parser and surrounding Node.JS tools such as Dredd as they can use the pure JavaScript version of Drafter.
The …

Bump minimum supported compiler versions

---

src/RefractDataStructure.cc
src/refract/Element.cc
src/refract/Element.h
src/refract/ElementInserter.h

- std::vector is not meant to be derived from; it doesn't even have a virtual destructor. In the future, this could cause strange behaviour.
- Parts of the interface continues to be implemented sub-optimally or inconsistently; changing this was not in scope of the task, therefore FIXME comments were added where relevant

Hold std::vector as member instead of base class in MemberElementCollection

---

src/RefractDataStructure.cc
test/fixtures/schema/array-restricted-to-type.json
test/fixtures/schema/array-restricted-to-types-complex.json

I found this refactoring while work on Enum implementation. 
I don't like to be part of Enum PR so i push it for merge
In tests there is just changed order of attributes in output

Simple refactoring - remove restful parameter from `RefractElementFromValue()`

---

drafter.xcodeproj/project.pbxproj
vcbuild.bat

Based on the list of supported compilers, we decided to allow most C++14 features in drafter.
This PR merely modifies build system configuration to append the -std=c++14 flag and not to append -std=c++11. The latter was necessary because current SC build configuration appends -std=c++11, overriding previous declarations.

Update build system to allow C++14

---

Dockerfile

There are problems with the apiary base image as it is pretty large and Docker Hub is having trouble building it.

Use base GCC image in Dockerfile

---

common.gypi

During performance testing of unrelated functionality, I've noticed the production build not to specify optimization flags. Some functions I expected to inline gave it away.
On an example running around `24s` in my environment, after introducing `-O3`, the run time decreased to `7s`.
Although the `O`-set of flags has different definitions in both GCC and clang, I suggest to go with `-O3` until we decide which optimizations applied by these aliases we want.

Compile with -O3

---

ext/snowcrash/ext/markdown-parser/markdownparser.xcodeproj/project.pbxproj
ext/snowcrash/snowcrash.xcodeproj/project.pbxproj
ext/snowcrash/src/BlueprintParser.h
ext/snowcrash/test/test-BlueprintParser.cc
test/fixtures/render/issue-328-1.json
test/fixtures/render/issue-328-2.json

Snowcrash should give out a circular reference error when an attirbutes
section is reference itself even when a description header node is present
before it.
This is actually a better fix for #328 than the one we did in #329

fix: Infinite loop issue

---

CHANGELOG.md

- Include missing breaking change on removing API Blueprint AST
- Include missing breaking change on Refract/API Elements
- Add consistency `*` over `-`

Update CHANGELOG for next release

---

tools/homebrew/drafter.rb

Drafter release was just bumped to v4.0.0-pre0, the pre1 branch doesn't exist.

Homebrew Formula Correct version

---

src/refract/dsd/Traits.h

```
$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
```
../src/refract/dsd/Traits.h:141:31: error: function 'erase' with deduced return type cannot be used before it is defined
return self().erase(it, std::next(it));
^
../src/refract/dsd/Traits.h:40:51: note: in instantiation of member function 'refract::dsd::container_traits<refract::dsd::Enum, std::__1::vector<std::__1::unique_ptr<refract::IElement, std::__1::default_delete<refract::IElement> >, std::__1::allocator<std::__1::unique_ptr<refract::IElement, std::__1::default_delete<refract::IElement> > > > >::erase' requested here
typename = …
```

Fix macOS clang compilation error

---

.gitignore
drafter.gyp
src/config.cc
src/config.h
src/main.cc
src/utils/log/Trivial.cc
src/utils/log/Trivial.h

- logs into file `drafter.log`
- disabled by default, enabled via command line option
- severities: debug, info, warning, error
- debug entries only logged when compiled with DEBUG
```
ENABLE_LOGGING; // called iff '--enable-log` or `-L` is given to drafter
// ...
LOG(debug) << "generating JSON Schema for " << e.element();
```

(util) trivial logger, enabled via cmd line option

---

tools/coverage.sh

Example:
```
$ tools/coverage.sh test/utils/test-Utf8.cc
```
Produces `gcov` annotated source files in `build/coverage/`

(tools) added simple tool running gcov

---

drafter.gyp
src/refract/JsonSchema.cc
src/refract/JsonSchema.h
test/refract/test-JsonSchema.cc

Implements a subset of JSON schema generation from API Elements,
+ NullElement,
+ BooleanElement,
+ StringElement,
+ ArrayElement,
+ EnumElement,
without any support for named types.
Note that `fixed` and `fixedType` apply to some of the above elements. `optional`, `required` and `nullable` do not. `samples` and `default` are generally irrelevant when generating schemas.
This PR does not change production code paths.

(json-schema) primitive types, array, enum

---

src/refract/JsonSchema.cc
src/refract/JsonSchema.h
test/refract/test-JsonSchema.cc

+ schemas of named types render into the `definitions` property
+ schemas of named types are referenced via `$ref` properties
+ array element with fixed attributed renders minItems and
additionalItems
+ minor fixes (spelling, unused typedefs etc.)

(json-schema) refs & named types in `definitions` 

---

src/ElementComparator.h
src/RefractDataStructure.cc
src/refract/JSONSchemaVisitor.cc
test/test-ElementComparator.cc

- predicates are now passed to ElementComparator instead of std::set
generators
- (cosmetic) introduced `Equal`

(optim) avoided use of std::set in ElementComparator

---

src/utils/Utf8.h

Removed an unused and meaningless defaulted constructor.
Now compiles on Apple LLVM version 9.1.0.
Fixes #539

Fix bug #539

---

.travis.yml
src/utils/Utf8.h

This obviously won't pass until #539 is resolved. This PR will allow us to test for changes which won't compile on macOS clang though.
/cc @tjanc

Test on macOS using Travis CI

---

tools/make-tarball.sh

In Drafter master (and 4 pre release) we moved gyp to be in tools/gyp (previously in ext) which causes problems with the generated release tar balls since gyp wouldn't be included.
This was discovered in https://github.com/apiaryio/drafter/issues/542#issuecomment-387804944. This fix makes it so that the tools/gyp directory is not deleted.

Fix tarball generation to include tools/gyp in tarball

---

.gitmodules

Catch is now at v1.9.7 (latest v1 release)
This is causing problems (see #544)

Catch repository was moved to catch org

---

tools/refract-filter.py

As `yaml.Loader` etc is used in the arguments for the function, even due to our other checks for `if yaml` the script fails on invocation without first installing pyyaml. This PR fixes the script to work with JSON if you don't have pyyaml installed.
```
$ ./tools/refract-filter.py test/fixtures/schema/array-fixed-inline-samples.json
Traceback (most recent call last):
File "./tools/refract-filter.py", line 17, in <module>
def yaml_load(stream, Loader=yaml.Loader, object_pairs_hook=OrderedDict):
AttributeError: 'NoneType' object has no attribute 'Loader'
```
```
$ ./tools/refract-filter.py test/fixtures/schema/array-fixed-inline-samples.json
{
"address": [
"city"
]
}
{
"$schema": "http://json-schema.org/draft-04/schema#",
"type": "object",
"properties": {
"address": {
"type": "array", …
```

Restore script to work without pyyaml

---

.circleci/config.yml

This nearly halfs the entire CI time on Circle CI.
Before:
After:

Allow 4 make jobs concurrently

---

common.gypi

We're relying on this functionality in Protagonist as Protagonist async parsing uses separate threads and our internal logger is using static.

Don't disable thread safe static for macOS

---

appveyor.yml
ext/snowcrash/test/test-ActionParser.cc
ext/snowcrash/test/test-BlueprintParser.cc
ext/snowcrash/test/test-ParametersParser.cc
ext/snowcrash/test/test-ResourceGroupParser.cc
ext/snowcrash/test/test-ResourceParser.cc
ext/snowcrash/test/test-SymbolIdentifier.cc
ext/snowcrash/test/test-snowcrash.cc
test/utils/test-Variant.cc
vcbuild.bat

- run debug builds on Appveyor
- if tests fail, Appveyor fails
- if tests fail, last 100 lines of `drafter.log` are dumped
Two bugs in tests surfaced:
- `test-Variant.cc`: too strict assert
- snowcrash tests: changed occurences of `Resource resource =` to `const Resource& resource =` due to invalid copy constructor of `snowcrash::Resource`; this suppresses issue #585 but does not fix it

(fix) fixed VS build

---

tools/clang-format-check.sh

I've pulled out the commit from https://github.com/apiaryio/drafter/pull/576 so we can fix the rules in separate step (as there is large branch in progress).
* Check clang-format for version 5
* exclude boost headers from checking
* replace grep by awk because of error code

Upgrade clang-format script

---

.circleci/config.yml

> CircleCI does not run workflows for tags unless you explicitly specify tag filters. Additionally, if a job requires any other jobs (directly or indirectly), you must use regular expressions to specify tag filters for those jobs.
Also an example from the same page on circleci documentation
```yml
workflows:
version: 2
build-n-deploy:
jobs:
- build:
filters:  # required since `deploy` has tag filters AND requires `build`
tags:
only: /.*/
- deploy:
requires:
- build
filters:
tags:
only: /^v.*/
branches:
ignore: /.*/
```

chore: Make sure tag gets tested on circleci

---

drafter.gyp
src/RefractDataStructure.cc
src/refract/ElementUtils.cc
src/refract/ElementUtils.h
src/refract/JsonValue.cc
src/utils/so/Value.cc
src/utils/so/Value.h
test/refract/test-JsonValue.cc

Includes minor fixes; not all corner cases are covered by integration tests.

JSON value s11n unit tests

---

.clang-format
src/drafter.h
src/refract/ElementIfc.h
src/refract/ExpandVisitor.cc
src/refract/TypeQueryVisitor.h
src/refract/dsd/Extend.cc
src/utils/Variant.h
tools/clang-format-check.sh
tools/clang-format-fix.sh

Updated our `.clang-format` to also list configuration options for newer clang-format versions; allows same results across different versions of clang-format.
This was achieved by taking a recent release of clang-format and letting it generate the new configuration from the old one.
```
clang-format --style=file -dump-config > .clang-format-new
```
The only modification made afterwards was setting `FixNamespaceComments: false`, which matches the behaviour of older versions.

Generalized clang-format config & fixed some style issues

---

test/fixtures/parse-result/error.json
test/test-RefractParseResultTest.cc

The fixture `error.apib` was untested and incorrect which this PR resolves.

Fix untested error.apib fixture

---

appveyor.yml

These are currently failing on master, attempting to resolve them in https://github.com/apiaryio/drafter/pull/673. Disabling integration tests in interim so we're not blocking development while we fix Aruba.

Disable integration tests on windows CI

---

CHANGELOG.md
common.gypi
src/refract/JsonSchema.cc
src/refract/dsd/Traits.h

Verified using example from #682.
Before:
```
$ ./bin/drafter 682.apib -l
Assertion failed: (false), function renderProperty, file ../src/refract/JsonValue.cc, line 95.
fish: './bin/drafter bb.apib -l' terminated by signal SIGABRT (Abort)
```
After:
```shell
$ ./bin/drafter 682.apib -l
OK.
```

Set NDEBUG on release builds

---

ext/snowcrash/README.md

Many of the things in the README are outdated, such as the build instructions, license information and CI links because snowcrash has been merged into Drafter.

Remove outdated information from snowcrash readme

---

src/refract/JsonSchema.cc

The lack of `{` `}` around an if-else statement caused clang-format to get confused and incorrectly indent subsequent functions which makes the file hard to follow.
I was a little confused as to why `renderSchema` for object had the logic for array and other types embedded until I realised that it does not, just the code is formatted strangely.

Fix formatting of JsonSchema

---

Gemfile
Gemfile.lock
features/step_definitions/file_content_step.rb
features/support/aruba_config.rb
features/support/env.rb

Extracted from https://github.com/apiaryio/drafter/pull/673, this PR resolves the "security" warnings from GitHub, for example when you push:
```
remote: GitHub found 1 vulnerability on apiaryio/drafter's default branch (1 moderate). To find out more, visit:
remote:      https://github.com/apiaryio/drafter/network/alerts
```

Update Aruba and other Ruby based dependencies

---

CHANGELOG.md
src/refract/ElementUtils.cc
test/fixtures/schema/issue-686.apib
test/fixtures/schema/issue-686.json
test/test-SchemaTest.cc

For some reason, the logic for inheriting "fixed" requires an object to have a value. An empty object should inherit fixed too.

Fix "fixed" type attribute not inheriting for empty objects

---

src/RefractDataStructure.cc
test/fixtures/mson/issue-699.apib
test/fixtures/mson/issue-699.json
test/test-RefractDataStructureTest.cc

Fixes #699 by skipping invalid One Of entries when translating MSON to
API Elements.
In the example in #699, the parser (snowcrash) should skip the invalid
One Of even before it arrives in semantic analysis. Because we are planning
a complete rewrite of our parser, this issue was fixed during
semantic analysis (drafter).

Skip invalid One Of entries

---

src/NamedTypesRegistry.cc
src/refract/ExpandVisitor.cc
test/fixtures/api/issue-702.apib
test/fixtures/api/issue-702.json
test/test-RefractAPITest.cc

- fixes #702 
Semantic analysis (drafter) was dependent on the parser (snowcrash) to short out circular dependencies of MSON types. If snowcrash failed to do so, we would fall into infinite loops resolving dependency paths in our type registry. That has been prevented.

Add some missing checks for circular references

---

.circleci/config.yml
cmake/unix-coverage.cmake

Generate test coverage when running ctest with the script `cmake/unix-coverage.cmake`.
* `gcov` coverage files are in `build/Testing/CoverageInfo/` after running
```
$drafter> ctest -S cmake/unix-coverage.cmake
```
For example:
```
-:    0:Source:/home/tj/projects/apiary/drafter/src/refract/dsd/Number.cc
-:    0:Graph:/home/tj/projects/apiary/drafter/build/src/CMakeFiles/drafter.dir/refract/dsd/Number.cc.gcno
-:    0:Data:/home/tj/projects/apiary/drafter/build/src/CMakeFiles/drafter.dir/refract/dsd/Number.cc.gcda
-:    0:Runs:1
-:    0:Programs:1
-:    1://
-:    2://  refract/dsd/Number.cc
-:    3://  librefract
-:    4://
-:    5://  Created by Thomas Jandecka on 04/09/2017
-:    6://  Copyright (c) 2017 Apiary Inc. All rights reserved.
-:    7://
-:    8:
-:    9:#include "Number.h"
-: …
```

Add coverage to CI via ctest_coverage

---

.circleci/config.yml
src/refract/JsonSchema.cc

GCC 4.8 is the oldest compiler we support with gyp (in Protagonist) and we've introduced compiler support regressions such as https://github.com/apiaryio/drafter/pull/691. This can be avoided in the future if we CI against this version.

Test on CI with gyp on GCC 4.8

---

CHANGELOG.md
src/refract/JsonSchema.cc
src/refract/JsonValue.cc
test/fixtures/mson/issue-709-b.apib
test/fixtures/mson/issue-709-b.json
test/fixtures/mson/issue-709.apib
test/fixtures/mson/issue-709.json
test/test-RefractDataStructureTest.cc

Support top level Reference Element when translating API Elements to JSON & JSON Schema

---

tools/make-tarball.sh

We're distributing GYP source (in `tools/`) and the GYP configuration which is no longer supported in the release tarballs, this PR removes GYP completely from these tarballs, CMake is the only supported way to build and install Drafter releases.
The release tarball script was a little outdated and tried to remove files that have been renamed (CircleCI config) or are non-existant. I've updated some of these rules too.
The tarball looks something like the following after this patch:
```
x drafter-v4.0.0-pre.7/
x drafter-v4.0.0-pre.7/CMakeLists.txt
x drafter-v4.0.0-pre.7/LICENSE
x drafter-v4.0.0-pre.7/test/
x drafter-v4.0.0-pre.7/cmake/
x drafter-v4.0.0-pre.7/configure
x drafter-v4.0.0-pre.7/CHANGELOG.md
x drafter-v4.0.0-pre.7/Makefile
x drafter-v4.0.0-pre.7/CTestConfig.cmake
x …
```

Remove GYP configuration from release tarballs

---

CHANGELOG.md
src/utils/so/JsonIo.cc
test/fixtures/mson/variable-property-name.json
test/utils/so/test-JsonIo.cc

(fix): issue #719 - escaping keys in generated JSON/JSON Schema

---

ext/snowcrash/ext/markdown-parser/src/MarkdownNode.cc
ext/snowcrash/ext/markdown-parser/src/MarkdownNode.h
ext/snowcrash/ext/markdown-parser/src/MarkdownParser.cc

As per https://github.com/apiaryio/drafter/pull/725#pullrequestreview-258008645, this probably isn't usful. Tools like lldb/gdb exist which can make debugging experiance better.

Remove markdown-parser debug logging

---

CMakeLists.txt
ext/snowcrash/CMakeLists.txt
ext/snowcrash/ext/markdown-parser/CMakeLists.txt
src/CMakeLists.txt
src/utils/Utf8.h

In Visual C++ 2015 Build Tools:
```
drafter> mkdir build
drafter> cd build
drafter/build> cmake .. -DCMAKE_INSTALL_PREFIX=..\install -DCMAKE_BUILD_TYPE=Release
drafter/build> cd ..
drafter> cmake --build build -t drafter-cli --config Release
drafter> cmake --build install -t drafter-cli --config Release
```
After a successful build, a standalone `drafter.exe` is located in `install/bin`.
* can be improved without too much effort by generating a Windows installer via CPack
* introduction of a CTest dashboard script is not in the scope of this PR
* debug build fails to load the debug version of `ucrtbase.dll`, called `ucrtbased.dll`; that's expected, as Visual C++ 2015 Build Tools don't ship the debug version

Windows cmake build

---

ext/snowcrash/src/Blueprint.h
ext/snowcrash/src/BlueprintSourcemap.h
ext/snowcrash/src/Platform.h
src/drafter.h

The APIs of snowcrash are no longer public facing and thus deprecation warnings at
build time is not necessary (`-Wdeprecations`).
I believe the whole structure is deprecated internally, not sure that having DEPRECATION on these specific properties adds any value.

Declassify internal APIs as deprecated

---

ext/snowcrash/src/MSON.h

Example:
```
c:\projects\drafter\ext\snowcrash\src\MSON.h(424): warning C4800: 'const mpark::monostate *': forcing value to bool 'true' or 'false' (performance warning) [C:\projects\drafter\build\ext\snowcrash\snowcrash.vcxproj]
BlueprintSourcemap.cc
```

Avoid Visual C++ warning c4800 in MSON.h

---

README.md

You can view a rendered version of the README chages at: https://github.com/apiaryio/drafter/blob/94082fa83847bb7b0adb4c87d4584285ec268124/README.md
This is a draft because the installation instructions are prepared for Drafter 4.0.0 major release and should be merged as we make the 4.0.0 release.

Update installation instructions for CMake

---

.circleci/config.yml
Dockerfile

I realised the docker image isn't tested nor updated from GYP to CMake, this pull request solves both. We are now building and running the image in CI and building using CMake.
I've refactored the drafter image a bit to use Alpine to shrink the size down, making use of separate environments for build and running so we can remove build dependency slices from the image. This makes the image around 1.8GB smaller.
```
$ docker images | grep drafter
drafter           96MB
apiaryio/drafter  1.86GB
```

Update docker image to build with CMake

---

ext/snowcrash/ext/markdown-parser/src/MarkdownNode.cc
ext/snowcrash/ext/markdown-parser/src/MarkdownNode.h
ext/snowcrash/ext/markdown-parser/src/MarkdownParser.cc
ext/snowcrash/ext/markdown-parser/src/MarkdownParser.h
ext/snowcrash/ext/markdown-parser/test/test-ByteBuffer.cc
ext/snowcrash/ext/markdown-parser/test/test-MarkdownParser.cc
ext/snowcrash/src/SignatureSectionProcessor.h
ext/snowcrash/src/snowcrash.cc
ext/snowcrash/test/snowcrashtest.h
ext/snowcrash/test/test-ActionParser.cc
ext/snowcrash/test/test-AssetParser.cc
ext/snowcrash/test/test-AttributesParser.cc
ext/snowcrash/test/test-BlueprintParser.cc
ext/snowcrash/test/test-DataStructureGroupParser.cc
ext/snowcrash/test/test-HeadersParser.cc
ext/snowcrash/test/test-MSONMixinParser.cc
ext/snowcrash/test/test-MSONOneOfParser.cc
ext/snowcrash/test/test-MSONTypeSectionParser.cc
ext/snowcrash/test/test-MSONUtility.cc
ext/snowcrash/test/test-ParameterParser.cc
ext/snowcrash/test/test-ParametersParser.cc
ext/snowcrash/test/test-PayloadParser.cc
ext/snowcrash/test/test-RelationParser.cc
ext/snowcrash/test/test-ResourceGroupParser.cc
ext/snowcrash/test/test-ResourceParser.cc
ext/snowcrash/test/test-SectionParser.cc
ext/snowcrash/test/test-Signature.cc
ext/snowcrash/test/test-ValuesParser.cc

https://github.com/apiaryio/drafter/pull/726 broken compatbility with MSVC which caused master to be unreleasable for a month. This PR reverts the changes that caused the problem to unblock releasing master. There were two problems, the code base couldn't be compiled on MSVC 2019:
```
ext\snowcrash\src\Just.h(21, 26): error C2131:  expression did not evaluate to a constant
ext\snowcrash\src\Just.h(21, 1): error C2440:  'noexcept': cannot convert from 'T' to 'bool
...
ext\snowcrash\src\Just.h(21, 26): message :  No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```
Protagonist CI couldn't complete on MSVC 2015 and caused an access violation causing the tests to exit.
This does mean that the test-asan CircleCI step will fail (it …

Fix compatbility with MSVC and GYP

---

src/ElementData.h
src/RefractDataStructure.cc
test/fixtures/mson/enum-variants.apib
test/fixtures/mson/enum-variants.json
test/fixtures/mson/issue-749-1.apib
test/fixtures/mson/issue-749-1.json
test/fixtures/mson/issue-749-2.apib
test/fixtures/mson/issue-749-2.json
test/test-RefractDataStructureTest.cc

closes #749 
Ignore enum duplicity if defined inline and later again in members
```
+ state: processed (enum)
+ Members
+ queued
+ processed
+ done
```

fix issue 749

---

.circleci/config.yml

Xcode 9 image contains macOS 10.13 which doesn't appear to be compatible with the latest version of Homebrew which now emits Ruby errors causing failing master.

Update to Xcode 11 bon Circle CI

---

Dockerfile
ext/snowcrash/CMakeLists.txt
ext/snowcrash/ext/markdown-parser/CMakeLists.txt
src/CMakeLists.txt
test/CMakeLists.txt

NOTE: Firstly most be added this one  https://github.com/apiaryio/sundown/pull/18
- build code with '-fPIC' option
- drafter-so target
- litle reorganization:
- introduce drofter-obj target
- drafter renamed to drafter-lib to conform naming
- dependent includes/libs to drafter-lib, drafter-so, drafter-cli are
now injected via drafter-obj instead of direct definitions

(fix) build dynamic lib

---

.circleci/config.yml

Comment asan-config to avoid run test
It is long-term problem and we decide to disable run test until we make fix in source code

temporary disable asan-test from circleci

---

test/test-CAPI.c

We are currently using C asserts as test assertions in our C API tests. That means our production builds don't include any assertions. A macro `REQUIRE` has been introduced, calling abort instead of assert; apart from printing some welcome annotations, like `__FILE__`, `__LINE__` and the tested expression itself.

fix (tests): C API test assertions are run in Release build

---

drafter.gyp
src/ConversionContext.cc
src/ConversionContext.h
src/MsonTypeSectionToApie.cc
src/NamedTypesRegistry.cc
src/RefractAPI.cc
src/RefractDataStructure.cc
src/RefractSourceMap.cc
src/Serialize.h
src/SerializeResult.cc
src/drafter.cc
test/CMakeLists.txt
test/draftertest.cc
test/draftertest.h

Some basic refactoring of ConversionContext:
- removed wrapper options, a needless abstraction
- moved some implementations to source files
- shortened two FarTooMuchLong method names
Stumbled upon this while adding an option to omit generating assets.

Improve readability of ConversionContext; remove WrapperOptions

---

ext/snowcrash/src/UriTemplateParser.cc
ext/snowcrash/test/test-UriTemplateParser.cc
test/fixtures/api/issue-702.json
test/fixtures/mson/issue-713.json

Uri template now gets hinting how to correctly encode invalid char

Improve URI tempate error reporting

---

src/drafter.cc
test/test-CAPI.c

Some pointers passed to the drafter C API have the character of output parameters. 
If set to `NULL`, their assignment could be skipped - perhaps the user is only testing for success.
This also contributes to simpler [examples](https://github.com/apiaryio/drafter/blob/tjanc/capi-allow-null-result/test/test-CAPI.c#L116).

C API to support output parameters `== NULL`

---

drafter.gyp
src/ConversionContext.cc
src/ConversionContext.h
src/RefractAPI.cc
src/drafter.cc
src/drafter.h
src/options.cc
src/options.h
test/CMakeLists.txt
test/ctesting.c
test/ctesting.h
test/draftertest.cc
test/test-CAPI.c

Builds on tjanc/refactor-payloads-2 to implement skipping asset generation as laid out in https://github.com/apiaryio/api-elements.js/pull/281 .
In more detail, two options are added to `drafter_parse_options` and the drafter C API:
- `skip_gen_bodies` [bool, default: false], when set, skips generating message body assets
- `skip_gen_body_schemas` [bool, default: false], when set, skips generating message body schema assets
Simple tests were added. Some test logic was moved into a seperate compilation unit `test/ctesting.cc`.
- wiring the new options into drafter CLI

C API options to allow skipping message body (schema) generation

---

CHANGELOG.md
src/CMakeLists.txt

* Drafter contains two new options for disabling messageBody and messageBodySchema generation from MSON. See the APIs `skip_gen_bodies` and `skip_gen_body_schemas` respectively.

Release 5.0.0

---

CHANGELOG.md
packages/drafter/src/refract/JsonSchema.cc
packages/drafter/test/fixtures/mson/fixed-type-array-primitive-nested.json
packages/drafter/test/fixtures/schema/array-fixed-type-attributes.json
packages/drafter/test/fixtures/schema/array-fixed-type-object.json
packages/drafter/test/fixtures/schema/issue-493-multiple-same-required.json
packages/drafter/test/fixtures/schema/variable-property-fixed-type.json
packages/drafter/test/fixtures/schema/variable-property-fixed-type2.json
packages/drafter/test/refract/test-JsonSchema.cc

This changeset optimises the generation of JSON Schema of fixed-type array's with a single element inside them to be placed directly inside "items", instead of inside an "anyOf" inside "items". A user was asking about this behaviour in https://github.com/apiaryio/api-blueprint/issues/450.
In terms of JSON Schema validation these behave the same, the new behaviour produces a smaller, clearer JSON Schema.
While doing so, I noticed that Drafter would produce an invalid schema in the case where there is an empty fixed-type array. Drafter would emit a sub-schema such as `{"anyOf": []}` which breaks the clause in [JSON Schema 2019-09 Section 9.2.1.2](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.2.1.2):
> This keyword's value MUST be a non-empty array.
Instead …

Optimise JSON Schemas generated for fixed-type arrays

---

drafter.gyp
packages/drafter/CMakeLists.txt
packages/drafter/src/MsonMemberToApie.cc

The file `MsonMemberToApie.cc` is effectively empty, containing no symbols and which emits compilation warning.
Closes #740

Remove empty source file

---

packages/drafter/CMakeLists.txt

This should make it easier for people to package drafter

fix: use default CMake directories
