- configure
Backport from snowcrash https://github.com/apiaryio/snowcrash/pull/304
> Run via `python` and ensure it's Python 2

- src/main.cc
- src/stream.h
- test/test-drafter.h
Should fix troubles with tr1
@pksunkara or @zdne  please test on OS X
> Remove tr1 from source codes due to troubles w\ building on diferent OS

- Gemfile.lock
- README.md
- appveyor.yml
- features/sourcemap.feature
- src/stream.h
- vcbuild.bat
Testing enviroment for build in appveyor.
Will ping when be ready to merge
> Appveyor CI - DO NOT MERGE (still)

- src/refract/ExpandVisitor.cc
- remove unused branch of code (ref as array)
- simplify `ExpandMembers()`
- join functions `ExpandReference()` and `CreateReference()` together
because of removed code
> Fix Ref Element expansion

- src/RefractAST.cc
- test/fixtures/mson/mson-multiline-description.json
> Refract MSON - double newline between descrpition and multiline description

- src/SerializeAST.cc
- src/cdrafter.cc
- src/main.cc
This is hotfix to handle exception.
Now program return safe from exception, but still there can be some non released memory.
Working on fix
> Hotfix to handle throwed exceptions

- src/RefractDataStructure.h
- src/refract/Element.h
- src/refract/ExpandVisitor.h
- src/refract/IsExpandableVisitor.cc
- src/refract/IsExpandableVisitor.h
Fix warnings from clang while compile
> Remove mismatch in forward decl (class vs struct)

- features/fixtures/refract.json
- features/fixtures/refract.yaml
- src/RefractAPI.cc
- src/RefractAPI.h
- src/SerializeAST.cc
- test/fixtures/api/attributes-references.apib
- test/fixtures/api/attributes-references.json
- test/test-RefractAPITest.cc
The attributes were getting expanded in MSON Refract in APIB AST but not in APIB Refract. This PR fixes that bug.
> Make sure references in attributes gets expanded in APIB Refract

- drafter.xcodeproj/project.pbxproj
This commit introduces Drafter CLI tool as a target in the Drafter
Xcode project
> Add drafter cli target

- src/RefractDataStructure.cc
move function `SelectNestedTypeSpecification` a few lines above
> Fix compilator error on clang

- src/RefractDataStructure.cc
- src/refract/Element.cc
- test/fixtures/mson/enum-members-description.apib
- test/fixtures/mson/enum-members-description.json
- test/test-RefractDataStructureTest.cc
This patch close #96 **MSON - array|enum - members description**
> fix members description form MSON

- src/RefractDataStructure.cc
- src/refract/SerializeCompactVisitor.cc
- test/fixtures/mson/array-sample.json
- test/fixtures/mson/enum-sample.json
- test/fixtures/mson/nontyped-array-sample.json
- test/fixtures/mson/nontyped-array.json
- test/fixtures/mson/object-sample.json
- test/fixtures/mson/oneof-sample.json
- test/fixtures/mson/typed-array-sample.json
- test/fixtures/mson/typed-array.json
- test/fixtures/render/array-samples.json
- test/fixtures/render/inheritance-array-sample.json
- test/fixtures/render/mixin-array-sample.json
- test/fixtures/render/object-samples.json
> Change serialization for "samples" and "default"

- src/cdrafter.h
This PR fixes something I was having an issue with when working with C-interface
> Add enum keyword when required

- src/config.cc
- add format and type to descriprion Fixes #99
- add warn while output and validation required together Fixes #90
> Resolve CLI enhacenment

- src/RefractAPI.cc
small refactoring for serialization of simple collections
> Change Headers element from ObjectElement to ArrayElement

- src/RefractAPI.cc
- src/Render.cc
- src/Render.h
- src/Serialize.h
- src/SerializeAST.cc
- src/SerializeSourcemap.cc
- test/fixtures/api/action-request-attributes.apib
- test/fixtures/api/action-request-attributes.json
- test/fixtures/render/action-request-attributes.apib
- test/fixtures/render/action-request-attributes.json
- test/test-RefractAPITest.cc
- test/test-RenderTest.cc
> Request attributes will now inherit action attributes

- src/refract/RenderJSONVisitor.cc
- test/fixtures/render/object-array-string.apib
- test/fixtures/render/object-array-string.ast.json
- test/test-RenderTest.cc
> Do not render empty elements within an array inside JSON visitor

- drafter.gyp
- drafter.xcodeproj/project.pbxproj
This PR updates Xcodeproj and also removes some unneeded dependencies from gyp file.
> Maintain Xcodeproj and Gyp file

- test/draftertest.h
This fixes a couple of issues that were never addressed in #152.
* Creates and uses a namespace for filename extensions
* Fixes a memory issue with a bad pointer
cc @klokane
> Minor test fixes

- .npmrc
This removes the `.npmrc` file from the repo and fixes a build issue from #160.
> Remove .npmrc file

- README.md
- features/fixtures/refract.sourcemap.json
- features/fixtures/refract.sourcemap.yaml
- src/RefractDataStructure.cc
- src/Serialize.h
- src/SerializeAST.cc
- src/SerializeAST.h
- src/SerializeResult.cc
- src/SerializeResult.h
- test/fixtures/api/mson.sourcemap.json
- test/test-RefractDataStructureTest.cc
Fixed memory leaks on
- create description
- double registration of Named Types in AST branch
> Fix memory leaks

- drafter.gyp
- src/refract/Element.h
- src/refract/PrintVisitor.cc
- src/refract/PrintVisitor.h
- src/refract/RenderJSONVisitor.cc
- src/refract/VisitorUtils.h
- src/refract/Visitors.h
PrintVisitor is a helper visitor, it just prints the refract element and
its sybelements to any `ostream` provided. Default is `std::cout`
> Add convenience PrintVisitor

- src/main.cc
This PR fixes #188 
Only drawback is there are 2 unnecessary objects created when `-l` option is given. `sos::Serialize* serializer` and `std::ostream* out`
> Do MSON validating and rendering when validate option is supplied

- .npmignore
> Include `drafter.js` and `mem` files in npm

- drafter.xcodeproj/project.pbxproj
- src/refract/JSONSchemaVisitor.cc
- src/refract/JSONSchemaVisitor.h
- src/refract/PrintVisitor.cc
- src/refract/RenderJSONVisitor.cc
- src/refract/VisitorUtils.cc
* We use a newline char before `{` on function signature lines in `.cc` file.
* `else` should be on a separate line
* If a condition in `for` or `if` or `while` spans more than a single line, we add an empty line at the beginning of the block.
* We always use `{` & `}` symbols even if the block is a single line
> Add files to xcodeproj and some style fixes

- drafter.gyp
- src/RefractDataStructure.cc
- src/refract/Element.cc
- src/refract/Element.h
- src/refract/ElementFwd.h
- src/refract/ExpandVisitor.cc
- src/refract/ExpandVisitor.h
- src/refract/IsExpandableVisitor.cc
- src/refract/JSONSchemaVisitor.cc
- src/refract/JSONSchemaVisitor.h
- src/refract/PrintVisitor.cc
- src/refract/PrintVisitor.h
- src/refract/RenderJSONVisitor.cc
- src/refract/RenderJSONVisitor.h
- src/refract/SerializeCompactVisitor.cc
- src/refract/SerializeCompactVisitor.h
- src/refract/SerializeVisitor.cc
- src/refract/SerializeVisitor.h
- src/refract/TypeQueryVisitor.cc
- src/refract/TypeQueryVisitor.h
- src/refract/VisitorUtils.cc
- src/refract/VisitorUtils.h
Introduced `EnumElement` instead of parasiting on `ArrayElement`
- cleanup code
> EnumElement implementation

- src/refract/JSONSchemaVisitor.cc
- src/refract/JSONSchemaVisitor.h
> Address review for PR#204

- drafter.xcodeproj/project.pbxproj
- src/NodeInfo.h
- src/SerializeAST.cc
- src/SerializeResult.cc
- src/refract/ElementInserter.h
Please review and merge. @klokane @w-vi
> Style fixes and Xcode maintenance

- src/refract/JSONSchemaVisitor.cc
- test/fixtures/api/attributes-named-type-mixin.json
- test/fixtures/mson/resource-nested-mixin.ast.json
- test/fixtures/render/mixin-object-sample.ast.json
- test/fixtures/render/object-mixin.ast.json
- test/fixtures/schema/mixin-simple.apib
- test/fixtures/schema/mixin-simple.json
- test/fixtures/schema/object-complex.json
- test/test-SchemaTest.cc
> Resolve mixins in JSONSchema generator

- emcc/emcbuild.sh
- emcc/test-drafter
These changes have one undesirable effect, drafter.js is two times slower than before :/
> Update and fix the drafter.js build and tests

- test/draftertest.h
By setting the environment variable `GENERATE` to `1`, `make test` will now re-generate incorrect fixtures. This is handy when making large changes which result in many fixture changes. You can run `make test`, verify all of the changes and then run `make test` with `GENERATE` set to `1` as follows to re-generate the fixtures:
$ env GENERATE=1 make test
This follows the same behaviour as [fury-adapter-swagger](https://github.com/apiaryio/fury-adapter-swagger/blob/d88abbae682caa9d3ab27c9deea855da8c39091e/test/adapter.js#L32-L36).
> Add a mechanism to re-generate incorrect test fixtures

- src/RefractAPI.cc
- test/fixtures/api/request-parameters.apib
- test/fixtures/api/request-parameters.json
- test/fixtures/api/request-parameters.sourcemap.json
- test/fixtures/circular/array-in-object.json
- test/fixtures/circular/array.json
- test/fixtures/circular/cross.json
- test/fixtures/circular/embed.json
- test/fixtures/circular/enum.json
- test/fixtures/circular/simple.json
- test/test-RefractAPITest.cc
- test/test-RefractSourceMapTest.cc
Depends on apiaryio/snowcrash#366 and apiaryio/snowcrash#367.
Need to update snowcrash submodule in this PR once the above PRs are merged.
> Added request parameters to refract

- src/RefractAPI.cc
- src/Render.cc
- test/draftertest.h
- test/fixtures/api/payload-attributes.apib
- test/fixtures/api/schema-custom.apib
- test/fixtures/api/schema-custom.json
- test/fixtures/api/schema-custom.sourcemap.json
- test/fixtures/api/xml-body.apib
- test/fixtures/api/xml-body.json
- test/fixtures/api/xml-body.sourcemap.json
- test/fixtures/render/content-type.ast.json
- test/test-RefractAPITest.cc
- test/test-RefractSourceMapTest.cc
This PR also changes the macros for the tests so that we can do the selective testing more easier.
> Render JSON Schema only if body content type is JSON

- src/refract/Element.cc
- src/refract/Element.h
- src/refract/JSONSchemaVisitor.cc
- src/refract/JSONSchemaVisitor.h
- src/refract/VisitorUtils.h
- test/fixtures/mson/variable-property-name.json
- test/fixtures/schema/one-of.json
- test/fixtures/schema/variable-property2.apib
- test/fixtures/schema/variable-property2.json
- test/test-SchemaTest.cc
First attempt to get the JSON Schema for variable property names ... please review, I might go thorught the code one more time to make it nice and refactor but more eyes will see more. @klokane
> Add variable properties to JSON Schema generator

- src/RefractDataStructure.cc
- src/refract/Element.cc
- src/refract/Element.h
- src/refract/JSONSchemaVisitor.cc
- src/refract/JSONSchemaVisitor.h
- src/refract/RenderJSONVisitor.cc
- src/refract/VisitorUtils.cc
- src/refract/VisitorUtils.h
- test/fixtures/api/mson.sourcemap.json
- test/fixtures/mson/variable-property-name.apib
- test/fixtures/mson/variable-property-name.json
- test/fixtures/schema/one-of.json
- test/fixtures/schema/variable-property.json
- test/fixtures/schema/variable-property2.apib
- test/fixtures/schema/variable-property2.json
- test/test-RefractDataStructureTest.cc
- test/test-SchemaTest.cc
Before merge, we need to resolve how to correctly handle JSON Schema for Variable property name
> Variable property name

- src/RefractSourceMap.h
- src/SerializeAST.cc
- src/refract/JSONSchemaVisitor.cc
- src/refract/SerializeCompactVisitor.cc
- src/refract/SerializeVisitor.cc
- test/fixtures/circular/mixed.json
- test/fixtures/circular/mixin-cross.json
- test/fixtures/circular/mixin-embed.json
- test/fixtures/circular/mixin-identity.json
- test/fixtures/circular/mixin-member.json
Automaticaly full rendering for elements with "SourceMaps"
> Smart Serialization for sourcemaps

- src/NamedTypesRegistry.cc
- src/NodeInfo.h
- src/RefractAPI.cc
- src/RefractDataStructure.cc
- src/RefractDataStructure.h
- src/RefractElementFactory.cc
- src/RefractSourceMap.h
- src/SerializeAST.cc
- src/SerializeResult.cc
- src/main.cc
- src/refract/JSONSchemaVisitor.cc
- src/refract/RenderJSONVisitor.cc
- src/refract/SerializeCompactVisitor.cc
- src/refract/SerializeCompactVisitor.h
- src/refract/SerializeVisitor.cc
- src/refract/SerializeVisitor.h
- test/draftertest.h
- test/fixtures/circular/mixed.json
- test/fixtures/circular/mixin-cross.json
- test/fixtures/circular/mixin-embed.json
- test/fixtures/circular/mixin-identity.json
- test/fixtures/circular/mixin-member.json
Need to rebased on current master.
> Resolve sourcemaps for throws in drafter

- features/fixtures/refract.json
- features/fixtures/refract.sourcemap.json
- features/fixtures/refract.sourcemap.yaml
- features/fixtures/refract.yaml
- src/RefractAPI.cc
- test/fixtures/api/action-request-attributes.json
- test/fixtures/api/request-only.json
- test/fixtures/api/request-parameters.json
- test/fixtures/api/request-parameters.sourcemap.json
- test/fixtures/api/transaction.json
- test/fixtures/api/transaction.sourcemap.json
> Serialize title for payloads in meta

- src/refract/VisitorUtils.cc
- src/refract/VisitorUtils.h
> Remove unused GetFirstSample

- drafter.gyp
- drafter.xcodeproj/project.pbxproj
- test/test-ApplyVisitorTest.cc
- test/test-ElementFactoryTest.cc
- test/test-ExtendElementTest.cc
Also added `src/refract` as an include_dir to `test-libdrafter` target in gyp.
> Xcode maintenance

- src/cdrafter.cc
Sorry, it was a bad edit which got into the commit.
> Correcting mistake from #290

- CHANGELOG.md
As we've internally discussed, this PR introduces a changelog file. This changelog files allows us to easily keep track of the changes we make, pull requests are expected to add an entry to the changelog file in the appropriate enhancements or bug fixes section.
I've written a changelog entry for the items which have been included into master.
The entries for previous releases we're copied from GitHub releases so you don't need to review their content, since these release we're already made with these release notes.
> Introduce a CHANGELOG

- src/main.cc
- src/stream.h
- test/draftertest.h
> replace auto_ptr

- CHANGELOG.md
> Update CHANGELOG for Drafter API

- README.md
I've re-ordered the usage section so that the command line tool is demonstrated first. I'd expect most readers are coming to Drafter to use it as a command line tool.
@klokane
> Document new API in README

- Makefile
- drafter.gyp
- drafter.xcodeproj/project.pbxproj
- src/drafter.cc
- src/drafter.h
- src/refract/Query.h
- test/test-CAPI.c
This updates the Xcode project for your changes @klokane
> Update Xcode for Drafter

- CHANGELOG.md
- src/refract/Element.h
- src/refract/ExpandVisitor.cc
- src/refract/IsExpandableVisitor.cc
- test/fixtures/oneof/expanded.apib
- test/fixtures/oneof/expanded.json
- test/test-OneOfTest.cc
> Fix "One Of" expanding #360

- src/RefractDataStructure.cc
- src/refract/JSONSchemaVisitor.cc
- test/fixtures/render/array-fixed-values.apib
- test/fixtures/render/array-fixed-values.ast.json
- test/test-RenderTest.cc
Fixes https://github.com/apiaryio/drafter/issues/193 but broke 4 tests (https://github.com/apiaryio/drafter/issues/371)
> Copy mson attributes for values

- CHANGELOG.md
- src/refract/Element.cc
- test/fixtures/schema/object-override.apib
- test/fixtures/schema/object-override.json
- test/test-SchemaTest.cc
> fix: Inheritance of member type should merge meta and description

- features/fixtures/ast.json
- features/fixtures/ast.sourcemap.json
- features/fixtures/refract.json
- features/fixtures/refract.sourcemap.json
- src/RefractDataStructure.cc
- src/RefractElementFactory.cc
- src/RefractSourceMap.h
- src/Serialize.cc
- src/Serialize.h
- test/fixtures/mson/check-bool-number-value-validity.apib
- test/fixtures/mson/check-bool-number-value-validity.json
- test/fixtures/mson/number-wrong-value.ast.json
- test/test-RefractDataStructureTest.cc
Not yet finished - do not merge.
> Warning on invalid value for Boolean/Number 

- CHANGELOG.md
- test/fixtures/mson/mixin-nonexistent.ast.json
- test/fixtures/mson/regression-269.ast.json
- test/fixtures/mson/resource-unresolved-reference.apib
- test/fixtures/mson/resource-unresolved-reference.ast.json
- test/fixtures/parse-result/error-warning.ast.json
- test/fixtures/parse-result/error-warning.ast.sourcemap.json
- test/fixtures/parse-result/error-warning.json
- test/fixtures/parse-result/error-warning.sourcemap.json
- test/fixtures/render/issue-328-1.ast.json
- test/test-RefractDataStructureTest.cc
> Updated snowcrash

- CHANGELOG.md
- src/RefractAPI.cc
- src/Render.cc
- src/Render.h
- test/fixtures/api/schema-custom-json.apib
- test/fixtures/api/schema-custom-json.json
- test/test-RefractAPITest.cc
This PR fixes the bug described in https://github.com/apiaryio/drafter/issues/392.
> fix: Correctly set content type for custom JSON Schema

- CHANGELOG.md
- drafter.gyp
- test/fixtures/syntax/issue-350.apib
- test/fixtures/syntax/issue-350.json
- test/test-SyntaxIssuesTest.cc
> bugfix: warn on action with non-absolut URI

- CHANGELOG.md
- src/refract/JSONSchemaVisitor.cc
- test/fixtures/schema/array-fixed-type-attributes.apib
- test/fixtures/schema/array-fixed-type-attributes.json
- test/test-SchemaTest.cc
`fixed-type` was ignored when it was an attributes of top level array.
> fix(JSONSchema): fixed-type ignored on array

- CHANGELOG.md
- src/refract/JSONSchemaVisitor.cc
- test/fixtures/schema/variable-property-fixed-type.apib
- test/fixtures/schema/variable-property-fixed-type.json
- test/test-SchemaTest.cc
> Handle `fixed-type` with variable property name

- src/refract/JSONSchemaVisitor.cc
- test/fixtures/schema/variable-property-fixed-type2.apib
- test/fixtures/schema/variable-property-fixed-type2.json
- test/test-SchemaTest.cc
Extends from https://github.com/apiaryio/drafter/pull/411 to handle the case where there is an fixed-type array of multiple items.
> JSON Schema generation for fixed-type variable property with multiple items

- drafter.gyp
This reverts commit 9ff6f08d1ff02fc7c47c57bbd8a650ec99ac8418.
> Revert "chore: Clean up gyp file"

- CHANGELOG.md
- src/refract/JSONSchemaVisitor.cc
- test/fixtures/render/inheritance-object-sample.ast.json
- test/fixtures/render/mixin-object-sample.ast.json
- test/fixtures/render/primitive-samples.ast.json
> fix(schema): Add property defaults to schema

- Dockerfile
depends on https://github.com/apiaryio/docker-base-images/pull/92
> chore: update base image to apiaryio/cpp

- CHANGELOG.md
- src/refract/JSONSchemaVisitor.cc
- src/refract/JSONSchemaVisitor.h
- test/fixtures/oneof/required.apib
- test/fixtures/oneof/required.json
- test/fixtures/oneof/required2.apib
- test/fixtures/oneof/required2.json
- test/test-OneOfTest.cc
So that we can release the bug which was fixed.
> Cherry picking #453

- CHANGELOG.md
- test/fixtures/mson/enum-variants.ast.json
- test/fixtures/mson/fixed-type-array-primitive-nested.apib
- test/fixtures/mson/fixed-type-array-primitive-nested.json
- test/test-RefractDataStructureTest.cc
> fix: Allow fixed-type when array nested types are primitive

- test/fixtures/api/schema-custom-json.apib
- test/fixtures/api/schema-custom-json.json
Fixture was set to be empty in 47827ee, not sure why this was the case. @klokane ?
> Restore deleted fixture

- .gitignore
- src/refract/Element.cc
- test/fixtures/render/mixin-override.apib
- test/fixtures/render/mixin-override.json
- test/test-RenderTest.cc
- added fixtures for #419 
- fixed #419 
- updated .gitignore
> Fixed ExtendElement merge strategy for RefElement member (bug #419)

- src/refract/Element.cc
- test/fixtures/syntax/mixed-inheritance-and-mixin.apib
- test/fixtures/syntax/mixed-inheritance-and-mixin.json
- test/test-SyntaxIssuesTest.cc
Please do not merge. Fixed but still isolating test case
> Fix crash - accessing RefElement via non resolved member

- src/utils/Utf8.h
- src/utils/so/YamlIo.cc
- test/utils/test-Utf8.cc
- implemented missing test
- removed irrelevant TODO
- enriched comments a bit
- minor renaming
> (utils) yaml serialization review addressed

- ext/snowcrash/src/BlueprintParser.h
- ext/snowcrash/src/ResourceGroupParser.h
- ext/snowcrash/src/ResourceParser.h
- ext/snowcrash/test/test-MSONPropertyMemberParser.cc
- ext/snowcrash/test/test-ResourceParser.cc
I gave up on trying to get drafter to compile on xcode
> refactor: Use C++14 more for a few things

- src/refract/ExpandVisitor.cc
- test/fixtures/render/issue-556.apib
- test/fixtures/render/issue-556.json
- test/test-RenderTest.cc
> (fix) fixed issue 556

- ext/snowcrash/src/ParameterParser.h
This code is doing nothing useful, I think it's some kind of legacy.
> Remove unused code

- Gemfile
- appveyor.yml
- vcbuild.bat
Gemfile
- fix version of aruba on tag v0.7.4
appveyor.yml
- use ruby 2.5
- download certificate
vcbuild.bat
- copy drafter.exe after build to working dir, to allow run in tests
> Update appveyor config to build after update

- src/RefractDataStructure.cc
- test/fixtures/mson/empty-sample.json
- test/fixtures/mson/enum-empty-default.json
> (fix) #567 empty default/sample handling

- .circleci/config.yml
- src/RefractDataStructure.cc
- test/test-ElementInfoUtils.cc
> Prevent pessimizing-move 

- common.gypi
- drafter.gyp
- src/utils/log/Trivial.cc
- src/utils/log/Trivial.h
> (fix) removed file logging from production build

- src/refract/ExpandVisitor.cc
- src/utils/so/Value.cc
- test/fixtures/schema/issue-664.apib
- test/fixtures/schema/issue-664.json
- test/refract/test-JsonSchema.cc
- test/test-SchemaTest.cc
> Fix duplicity in generated scheme with swapped order of member object wit `fixed-type`

- src/refract/JsonSchema.cc
- src/refract/JsonValue.cc
- test/fixtures/mson/issue-699.json
- test/fixtures/mson/issue-713.apib
- test/fixtures/mson/issue-713.json
- test/test-RefractDataStructureTest.cc
+ avoid aborts on invalid elements
+ fix bugs involving infinite recursion on some invalid elements, resulting in segfaults
fixes #713
> Avoid aborts on invalid elements in backend

- CHANGELOG.md
- src/ElementComparator.h
- src/RefractDataStructure.cc
- test/fixtures/mson/issue-718.apib
- test/fixtures/mson/issue-718.json
- test/test-RefractDataStructureTest.cc
> (fix): issue 817

- appveyor.yml
- cmake/win_release.cmake
Remove Windows GYP CI and introduce CMake instead.
- also removed some redundant windows builds in the process
> Switch Windows CI from GYP to CMake

- src/RefractDataStructure.cc
Little bi more functional way refactoring
- remove overused template parameter from `DescriptionToRefract()`
- remove `struct Join` and replace it by `accumulate` && lambda combo
- repace `ValueHasMembers()` for-loop by functional `find_if`
> Refactor - replace some part of RefractDataStructure by functional way

- .gitmodules
- CMakeLists.txt
- drafter.gyp
- src/CMakeLists.txt
- src/ContentTypeMatcher.cc
- src/ContentTypeMatcher.h
- src/RefractAPI.cc
- src/Render.cc
- src/Render.h
- src/parser/Mediatype.cc
- src/parser/Mediatype.h
- test/CMakeLists.txt
- test/parser/test-MediaType.cc
- test/parser/test-Mediatype.cc
- test/test-ContentTypeMatcher.cc
It also replace JSON(Schema)Regex by MediaTypeMatcher
> introduce pegtl based parser::mediatype

- packages/drafter/CMakeLists.txt
relates to https://github.com/Homebrew/homebrew-core/pull/137918
> fix: patch version to match with the release
